main()
{
  // cleanup obsolete library location
  fwInstallation_cleanupObsoleteFiles("unDistributedControl",
    makeDynString("scripts/libs/unDistributedControl.ctl",
                  "config/unDistributedControl.config",
                  "msg/en_US.iso88591/unDistributedControl.cat",
                  "scripts/unDistributedControl/unDistributedControl.preinit"
                 ));
   fwInstallation_cleanupObsoleteFiles("unDistributedControl", makeDynString("help/en_US.iso88591/unDistributedControl-ReleaseNotes.txt"), true);
   fwInstallation_cleanupObsoleteFiles("unDistributedControl", makeDynString("help/en_US.utf8/unDistributedControl/scripts"), true);
}